In [1]:
import glob
import numpy as np

data_sum = np.zeros(3609)

# 遍历当前目录下的所有.csv文件
for filename in glob.glob('./predict_test*.csv'):
    # 使用numpy的loadtxt读取csv文件内容
    data = np.loadtxt(filename, delimiter=',') # 假设csv文件的分隔符为逗号
    print(f'文件名: {filename}')
    print('数据:')
    print(data)
    data_sum = data_sum + data
#     print(data_sum)
    print('-' * 40) # 打印分隔线以区分不同文件的输出

data_mean = data_sum/len(glob.glob('./predict_test*.csv'))
print(len(glob.glob('./predict_test*.csv')))
print(data_mean)

np.savetxt("data_mean.csv",data_mean, delimiter=",")

文件名: .\predict_test_01.csv
数据:
[0.03047333 0.03028667 0.02997333 ... 0.42675333 0.42811333 0.43106667]
----------------------------------------
文件名: .\predict_test_02.csv
数据:
[0.03074    0.03045333 0.03006    ... 0.4202     0.42166667 0.42431333]
----------------------------------------
文件名: .\predict_test_03.csv
数据:
[0.03151333 0.03114667 0.03054    ... 0.43222    0.43342    0.43652   ]
----------------------------------------
文件名: .\predict_test_04.csv
数据:
[0.03114    0.03060667 0.03002667 ... 0.42102667 0.42254    0.42552   ]
----------------------------------------
文件名: .\predict_test_05.csv
数据:
[0.03063333 0.0304     0.02995333 ... 0.41516667 0.41673333 0.41932667]
----------------------------------------
文件名: .\predict_test_06.csv
数据:
[0.03105333 0.03056667 0.03009333 ... 0.42836    0.42956    0.43259333]
----------------------------------------
文件名: .\predict_test_07.csv
数据:
[0.03061333 0.03052    0.02971333 ... 0.42889333 0.43008667 0.43306667]
---------------------------------