In [1]:
import cv2
import numpy as np

img = cv2.imread("Image/0.30/0.30mgmL-1_18.png", cv2.IMREAD_COLOR)

In [2]:
# Select a specific color region of the solution in the bottle, 
# and then calculate the average by summing the B, G, and R values.

# height
c1 = int(0.50*img.shape[0])
c2 = int(0.70*img.shape[0])

# width
d1 = int(0.45*img.shape[1])
d2 = int(0.55*img.shape[1])

arr = np.zeros((1,3), dtype=int)

for c in range(c1,c2):
    for d in range(d1,d2):
        arr += img[c,d]
        
arr_average = arr/((c2-c1)*(d2-d1)) 

print(arr_average)
solution_color = arr_average

arr_solution = img[c1:c2,d1:d2]
cv2.imwrite('solution.png', arr_solution)

[[ 26.0484614   12.04514465 106.52146674]]


True

In [3]:
# Select a specific area on the outside of the bottle as background noise, 
# and calculate the average by summing the B, G, and R values.

# height
c1 = int(0.50*img.shape[0])
c2 = int(0.70*img.shape[0])

# width
d1 = int(0.80*img.shape[1])
d2 = int(0.90*img.shape[1])

arr = np.zeros((1,3), dtype=int)

for c in range(c1,c2):
    for d in range(d1,d2):
        arr += img[c,d]
        
arr_average = arr/((c2-c1)*(d2-d1))  
arr_average = arr/((c2-c1)*(d2-d1))  

print(arr_average)
backgroud_color = arr_average

arr_backgroud = img[c1:c2,d1:d2]
cv2.imwrite('backgroud.png', arr_backgroud)


[[206.01464898 223.89681224 236.79712548]]


True

In [4]:
# Take the difference between the solution color and the background color.

import numpy as np
np.set_printoptions(suppress=True)

diff_color=abs(solution_color-(255-backgroud_color))
print(diff_color)

[[22.93688963 19.05804312 88.31859222]]
